### ISSUE TITLE
Submit button is missing from contact form

### ISSUE THREAD

**Issue by jchiatt** [DevLifts/devlifts-static#15]
It seems to be in the markup, but is getting removed somewhere between deploying to Netlify and the user hitting the page.

https://devlifts.io/contact

**Comment by KempfCreative** [comment]
@jchiatt I just checked this on Firefox, and I was able to see the submit button, and submit a form as well :)

**Comment by jchiatt** [comment]
Fixed in https://github.com/DevLifts/devlifts-static/commit/489d60e7d4de09c3855044f19b3ebd4e9d02fe0e
